name: C++ CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libcurl4-openssl-dev nlohmann-json3-dev

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cmake curl nlohmann-json

    - name: Configure CMake
      working-directory: ./cpp
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      working-directory: ./cpp/build
      run: make

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cpp-libraries-${{ matrix.os }}
        path: cpp/build/libx402.*



