name: Multi-Language Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build release
      working-directory: ./rust
      run: cargo build --release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: rust-${{ matrix.os }}
        path: rust/target/release/x402*

  build-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - name: Build
      working-directory: ./go
      run: |
        GOOS=linux GOARCH=amd64 go build -o x402-linux-amd64 ./cmd/x402-server
        GOOS=darwin GOARCH=amd64 go build -o x402-darwin-amd64 ./cmd/x402-server
        GOOS=windows GOARCH=amd64 go build -o x402-windows-amd64.exe ./cmd/x402-server
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: go-binaries
        path: go/x402-*

  publish-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Build
      working-directory: ./python
      run: |
        pip install build
        python -m build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages-dir: python/dist/

  create-release:
    needs: [build-rust, build-go, publish-python]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          rust-*/*
          go-binaries/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



